# Author: 23f3001275@ds.study.iitm.ac.in
# Business Case: Employee Performance Analysis

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------------------------------------------
# 1) LOAD EMPLOYEE DATA (FROM PROVIDED CSV SAMPLE)
# ---------------------------------------------------

from io import StringIO

csv_data = """employee_id,department,region,performance_score,years_experience,satisfaction_rating
EMP001,Operations,Europe,87.22,9,4.2
EMP002,IT,North America,69.31,10,3.8
EMP003,Operations,Europe,83.3,3,4.9
EMP004,Sales,Europe,82.36,14,3.7
EMP005,Operations,Europe,71.31,6,3.1
"""

df = pd.read_csv(StringIO(csv_data))

# ---------------------------------------------------
# 2) FREQUENCY COUNT FOR FINANCE DEPARTMENT
# ---------------------------------------------------

finance_count = (df["department"] == "Finance").sum()
print("Frequency count for Finance department:", finance_count)

# ---------------------------------------------------
# 3) HISTOGRAM OF DEPARTMENTS
# ---------------------------------------------------

plt.figure(figsize=(8,5))
sns.countplot(x="department", data=df, palette="muted")
plt.title("Employee Count per Department")
plt.xticks(rotation=45)
plt.tight_layout()

# Save the histogram image
plt.savefig("histogram.png")

# ---------------------------------------------------
# 4) GENERATE HTML FILE
# ---------------------------------------------------

html_content = f"""
<html>
<head><title>Employee Performance Visualization</title></head>
<body>
<h2>Employee Performance Analysis</h2>
<p><b>Frequency count for Finance department:</b> {finance_count}</p>
<img src="histogram.png" alt="Histogram">
<p>Generated by: 23f3001275@ds.study.iitm.ac.in</p>
</body>
</html>
"""

with open("employee_analysis.html", "w") as f:
    f.write(html_content)

print("HTML file generated: employee_analysis.html")
