# Author: 23f3001275@ds.study.iitm.ac.in
# Business Case: Employee Performance Analysis

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# -------------------------
# 1. CREATE / LOAD DATA
# -------------------------

# Sample dataset of 100 employees
data = {
    "Employee_ID": range(1, 101),
    "Department": [
        "Finance", "Operations", "HR", "IT", "Sales", "Marketing", "Legal", "R&D"
    ] * 12 + ["Finance", "Operations", "IT", "HR"]
}

df = pd.DataFrame(data)

# -------------------------
# 2. CALCULATE FREQUENCY COUNT FOR FINANCE
# -------------------------

finance_count = (df["Department"] == "Finance").sum()
print("Frequency count of Finance department:", finance_count)

# -------------------------
# 3. CREATE HISTOGRAM
# -------------------------

plt.figure(figsize=(8,5))
sns.countplot(x="Department", data=df, palette="viridis")
plt.title("Employee Count per Department")
plt.xticks(rotation=45)
plt.tight_layout()

# Save plot
plt.savefig("histogram.png")

# -------------------------
# 4. SAVE OUTPUT AS HTML
# -------------------------

html_content = f"""
<html>
<head><title>Employee Performance Visualization</title></head>
<body>
<h2>Employee Performance Analysis</h2>
<p><b>Frequency count for Finance department:</b> {finance_count}</p>
<img src="histogram.png" alt="Histogram">
<p>Generated by: 23f3001275@ds.study.iitm.ac.in</p>
</body>
</html>
"""

with open("employee_analysis.html", "w") as file:
    file.write(html_content)

print("HTML file generated: employee_analysis.html")
